import json
import logging
from datetime import datetime
from nodes import (
    ScientistNode,
    PhilosopherNode,
    create_initial_state,
    MemoryNode,
    JudgeNode,
    export_graph_dot_from_history,
)

MAX_TURNS = 8  # 4 arguments per agent

# Setup logging to file and console
logger = logging.getLogger("debate")
logger.setLevel(logging.DEBUG)
fmt = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")

fh = logging.FileHandler("debate_full.log", encoding="utf-8")
fh.setLevel(logging.DEBUG)
fh.setFormatter(fmt)
logger.addHandler(fh)

ch = logging.StreamHandler()
ch.setLevel(logging.INFO)
ch.setFormatter(fmt)
logger.addHandler(ch)


def run_debate(topic: str):
    logger.info("=== Multi-Agent Debate System ===")
    logger.info(f"Topic: {topic}")
    print("\n=== Multi-Agent Debate System ===")
    print(f"Topic: {topic}\n{'-'*60}")

    state = create_initial_state(topic)
    scientist = ScientistNode()
    philosopher = PhilosopherNode()
    memory = MemoryNode()
    judge = JudgeNode()

    # structured log to dump at end
    structured_log = []
    seen_arguments = set()

    for turn in range(MAX_TURNS):
        expected_agent = "Scientist" if turn % 2 == 0 else "Philosopher"
        # enforce turn order (defensive check)
        if expected_agent == "Scientist":
            state = scientist(state)
            speaker = "Scientist"
            argument = state["last_scientist"]
        else:
            state = philosopher(state)
            speaker = "Philosopher"
            argument = state["last_philosopher"]

        # Validate not empty
        if not argument or not argument.strip():
            logger.error(f"Empty argument generated by {speaker} at round {turn+1}")
            raise RuntimeError("Empty argument generated; aborting.")

        # Validate repetition
        if argument in seen_arguments:
            logger.error(f"Argument repetition detected at round {turn+1} by {speaker}.")
            raise RuntimeError("Argument repetition detected.")
        seen_arguments.add(argument)

        # Append to memory node
        memory_entry = {
            "round": turn + 1,
            "speaker": speaker,
            "argument": argument,
            "timestamp": datetime.utcnow().isoformat() + "Z",
        }
        memory.update(memory_entry)

        # Log outputs
        log_line = f"[Round {turn+1}] {speaker}: {argument}"
        logger.info(log_line)
        structured_log.append({"node": speaker, "round": turn+1, "argument": argument})
        print(f"[Round {turn+1}] {speaker}: {argument}\n")

    # After all rounds, run judge
    judgment = judge.run({"memory": memory.memory, "topic": topic})
    logger.info("=== Debate Complete ===")
    logger.info(f"Winner: {judgment['winner']}")
    logger.info("Justification: " + judgment["justification"])

    # Save plain text log (compat with your previous output)
    with open("debate_log.txt", "w", encoding="utf-8") as f:
        for entry in memory.memory:
            f.write(f"{entry['speaker']}: {entry['argument']}\n")

    # Save structured graph log
    with open("debate_graph_log.json", "w", encoding="utf-8") as f:
        json.dump({
            "topic": topic,
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "memory": memory.memory,
            "judgment": judgment
        }, f, indent=2, ensure_ascii=False)

    # Export a simple DOT DAG made from the history
    dot_path = export_graph_dot_from_history(memory.memory, path="debate_graph.dot")
    logger.info(f"Wrote DAG dot file: {dot_path}")

    # Save final judgment text
    with open("final_judgment.txt", "w", encoding="utf-8") as f:
        f.write(f"Winner: {judgment['winner']}\n")
        f.write(f"Justification: {judgment['justification']}\n\n")
        f.write("Full Summary:\n")
        f.write(judgment["summary"])

    print("\n Debate complete.")
    print("Files written: debate_log.txt, debate_full.log, debate_graph_log.json, debate_graph.dot, final_judgment.txt")
    print("Structured JSON log: debate_graph_log.json")


if __name__ == "__main__":
    topic = input("Enter topic for debate: ").strip()
    if not topic:
        print("Please provide a topic.")
    else:
        run_debate(topic)
